### ISSUE TITLE
io.configure error

### ISSUE THREAD

**Issue by artsrun-gasparyan** [sambaker/AGS-Sample#4]
Hello,

When I attempt to run the server I get the following error which I believe is because io.configure got depreciated. I'm not quiet sure how to fix this. Overall it seems to have trouble with few methods in socket.io version 1.xx

C:\AGS-Sample-master\AGS-Sample-master\server\AGS-Server\server.js:11
io.configure('production', function(){
   ^
TypeError: Object #<Server> has no method 'configure'
    at Object.<anonymous> (C:\AGS-Sample-master\serve
r\AGS-Server\server.js:11:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by sambaker** [comment]
See the socket.io docs for info here:
http://socket.io/docs/migrating-from-0-9/#configuration-differences
Some of those configuration options like log level are deprecated, so you can leave those out, the ones that are still valid can be passed as shown in that link.
If you get this working, would be great if you could submit a pull request for the changes.

**Comment by artsrun-gasparyan** [comment]
I downgraded to 0.9 for testing by doing 
npm uninstall socket.io
npm install socket.io@0.9.0

also switched to socket 0.9.16 for client
"http://cdnjs.cloudflare.com/ajax/libs/socket.io/0.9.16/socket.io.min.js"

If I'm able to get the testing working I'll update it to latest socket.io version.
